### PR TITLE
Add MPI support

### PR DESCRIPTION
**Pull request by mrakitin**
This PR is a follow-up on https://github.com/conda-forge/staged-recipes/pull/15729#issuecomment-890171162 to add MPI support to this package. I restructured the `meta.yaml` to use the `outputs:` section to enable 2 types of artifacts. Originally we maintained a dedicated feedstock in https://github.com/nsls-ii-forge/arpack-mpi-feedstock, but it makes sense to combine the two to consistently maintain both of the libraries. The MPI builds were failing for Windows and OSX arm64, so I currently excluded those platforms for the MPI-enabled library. The `arpack-mpi` is needed for the https://github.com/NSLS-II/edrixs package, that will use this dependency (similarly to the deprecated/archived https://github.com/nsls-ii-forge/edrixs-feedstock).

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #44.

### CODE REVIEW

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Comment by mrakitin** [comment]
@jschueller, this is ready for your review. Will you have a chance to review/merge in the coming days? We'd like to have this dependency soon to proceed with packaging of `edrixs`. Please note, that packaging of the no-MPI version remains the same; the MPI-enabled version will be posted as a separate package https://anaconda.org/conda-forge/arpack-mpi. I appreciate your feedback, thanks in advance!

**Comment by mrakitin** [comment]
@conda-forge/core, I was unable to get a review from the maintainer. Could you please step in? Thanks!

**Review by beckermr — CHANGES_REQUESTED** [review]
This needs to follow the docs better I think: https://conda-forge.org/docs/maintainer/knowledge_base.html#message-passing-interface-mpi

**Comment by mrakitin** [comment]
@beckermr, thanks for the suggestion. It's now following the documentation in #46. Could you please review that one?

**Pull request closed without merging**
