### PR TITLE
Add a stricter `run_export`

### PR DESCRIPTION
**Pull request by mrakitin**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
you'll likely need to mark the old arpack builds with number 0 at this version broken to be safe

**Comment by mrakitin** [comment]
> you'll likely need to mark the old arpack builds with number 0 at this version broken to be safe

That makes sense, thanks! <strike>How would I go about it? Is there a repo for such marks?</strike>

Overall, is the approach here right?

**Comment by mrakitin** [comment]
https://github.com/conda-forge/admin-requests/pull/486 is for marking the earlier builds as broken.

**Comment by mrakitin** [comment]
Thanks, @beckermr!

**Pull request merged**
